import { ArrowRight, BriefcaseBusiness, ExternalLink, GraduationCap, Mail, UserRound } from "lucide-react";
import { useContactController } from "../controllers/useContactController";
import { projects, technologies } from "../models/portfolio";

export function PortfolioView() {
  const { status, handleSubmit } = useContactController();
  return <main>
    <header className="site-header"><a className="brand" href="#inicio"><span className="brand-avatar">KS</span><strong>Karoline Sirati</strong></a><nav><a href="#sobre">Sobre mim</a><a href="#experiencia">Experiência</a><a href="#projetos">Projetos</a><a href="#formacao">Formação</a><a href="#contato">Contato</a></nav></header>
    <section className="hero section-shell" id="inicio"><div className="hero-copy"><span className="eyebrow">Olá, eu sou</span><h1>Karoline Sirati</h1><h2>Desenvolvedora Full Stack</h2><p className="stack-line">Go <span>•</span> React <span>•</span> TypeScript</p><p className="hero-description">Construindo soluções digitais com código limpo e foco em pessoas.</p><div className="hero-actions"><a className="button primary" href="#projetos">Ver projetos <ArrowRight size={18}/></a><a className="button secondary" href="https://github.com/KarolSirati" target="_blank" rel="noreferrer"><b>GH</b> GitHub</a><a className="button secondary" href="https://www.linkedin.com/in/karoline-sirati/" target="_blank" rel="noreferrer"><b>in</b> LinkedIn</a></div></div><div className="portrait-wrap"><div className="portrait-backdrop"/><img src="/karoline.png" alt="Karoline Sirati"/></div></section>
    <section className="highlight section-shell" id="experiencia"><div className="experience-summary"><BriefcaseBusiness/><div><span>Experiência</span><strong>Grupo Globo</strong><small>ago/2025 — atual</small></div></div><div className="tech-summary"><span className="tech-label">&lt;/&gt; <strong>Tecnologias</strong></span><div className="tech-list">{technologies.map(tech=><span key={tech}>{tech}</span>)}</div></div></section>
    <section className="projects section-shell" id="projetos"><div className="section-heading"><div><span className="section-icon">▦</span><h2>Projetos em destaque</h2></div><a href="https://github.com/KarolSirati" target="_blank" rel="noreferrer">Ver todos no GitHub <ArrowRight size={17}/></a></div><div className="project-grid">{projects.map(project=><article className="project-card" key={project.title}><img src={project.image} alt={`Captura do projeto ${project.title}`}/><div className="project-content"><h3>{project.title}</h3><span>{project.subtitle}</span><p>{project.description}</p><div className="project-actions"><a className="button primary small" href={project.repository} target="_blank" rel="noreferrer"><b>GH</b> Repositório</a><a className="button secondary small" href={project.demo} target="_blank" rel="noreferrer"><ExternalLink size={17}/> Ver demo</a></div></div></article>)}</div></section>
    <section className="details section-shell" id="sobre"><article><UserRound/><div><h2>Sobre mim</h2><p>Desenvolvedora Full Stack em início de carreira, com experiência em produtos digitais e aprendizado contínuo. Trabalho com Go, React e TypeScript, criando soluções claras, acessíveis e bem estruturadas.</p></div></article><article id="formacao"><GraduationCap/><div><h2>Formação</h2><p>Análise e Desenvolvimento de Sistemas — Universidade Veiga de Almeida.</p><p>Formações complementares em desenvolvimento web e computação em nuvem.</p></div></article></section>
    <section className="contact section-shell" id="contato"><div className="contact-copy"><Mail/><div><span className="eyebrow">Contato</span><h2>Vamos conversar?</h2><p>Estou aberta a oportunidades e trocas sobre tecnologia.</p></div></div><form onSubmit={handleSubmit}><label>Nome<input name="name" required minLength={2} placeholder="Seu nome"/></label><label>E-mail<input name="email" type="email" required placeholder="voce@empresa.com"/></label><label className="full-field">Mensagem<textarea name="message" required minLength={10} placeholder="Escreva sua mensagem"/></label><div className="form-footer"><button className="button primary" disabled={status==="sending"}>{status==="sending"?"Enviando...":"Enviar mensagem"}<ArrowRight size={18}/></button><span>{status==="success"&&"Mensagem recebida!"}{status==="error"&&"Não foi possível enviar. Verifique se a API Go está ativa."}</span></div></form></section>
    <footer className="section-shell"><span>Karoline Sirati</span><span>Go • React • TypeScript</span><div><a href="https://github.com/KarolSirati"><b>GH</b></a><a href="https://www.linkedin.com/in/karoline-sirati/"><b>in</b></a></div></footer>
  </main>;
}
